services:
  peacemusic:
    build: .
    network_mode: "host" # Enables IPv6 (on Linux) and better performance
    restart: always
    env_file:
      - .env
    volumes:
      - ./music_files:/app/music_files
      # Persist cookies if they exist
      - ./cogs/cookies.txt:/app/cogs/cookies.txt
